import { describe, expect, it } from "vitest";

import { ReportGenerator, toReleaseManifest } from "../../src/index";
import { stubs } from "../stubs";

describe("ReleaseManifestFormatter", () => {
  it("creates a deterministic tested-together hash from scenario ids and statuses", () => {
    const run = stubs.testRunResult({
      startedAtMs: 1000,
      finishedAtMs: 2000,
      gitSha: "abc123",
      ci: { name: "github", branch: "release/1.2.0" },
      testCases: [
        stubs.testCaseResult({
          id: "b",
          status: "failed",
          sourceFile: "src/b.story.test.ts",
          sourceLine: 2,
          story: stubs.storyMeta({ scenario: "Feature B" }),
        }),
        stubs.testCaseResult({
          id: "a",
          status: "passed",
          sourceFile: "src/a.story.test.ts",
          sourceLine: 1,
          story: stubs.storyMeta({ scenario: "Feature A" }),
        }),
      ],
    });

    const manifest = toReleaseManifest(run);

    expect(manifest.run.branch).toBe("release/1.2.0");
    expect(manifest.run.gitSha).toBe("abc123");
    expect(manifest.scenarios.map((scenario) => scenario.id)).toEqual(["a", "b"]);
    expect(manifest.testedTogetherHash).toBe(
      "8993ca6c0b80f7469b47433a28247890654156b8555415b38e9610ed59ef8034",
    );
  });

  it("is generated by ReportGenerator", async () => {
    const writes = new Map<string, string>();
    const generator = new ReportGenerator(
      {
        formats: ["release-manifest"],
        outputDir: "reports",
        outputName: "v1.2.0",
      },
      {
        writeFile: async (filePath, content) => {
          writes.set(filePath, content);
        },
      },
    );

    const result = await generator.generate(stubs.testRunResult());

    expect(result.get("release-manifest")).toEqual([
      "reports/v1.2.0.release-manifest.md",
    ]);
    expect(writes.get("reports/v1.2.0.release-manifest.md")).toContain(
      "Tested-together hash:",
    );
  });
});
