import Ajv2020 from "ajv/dist/2020";
import { describe, expect, it } from "vitest";
import * as fs from "node:fs";

import { canonicalizeRun } from "executable-stories-core/converters/acl/canonicalize";
import {
  ScenarioIndexJsonFormatter,
  toScenarioIndex,
} from "../../src/formatters/scenario-index-json";
import { createMultipleTestCasesRun } from "../fixtures/raw-runs/basic";
import { toStoryReport } from "executable-stories-core/converters/story-report";
import { ReportGenerator } from "../../src/index";

describe("ScenarioIndexJsonFormatter", () => {
  it("emits schema-valid scenario index JSON with stable ids", () => {
    const run = canonicalizeRun(createMultipleTestCasesRun());
    const index = new ScenarioIndexJsonFormatter().toIndex(run);

    expect(index.schemaVersion).toBe("1.0");
    expect(index.scenarios).toHaveLength(3);
    expect(index.scenarios.map((scenario) => scenario.id)).toEqual([
      "feature-src-auth-login-test--user-can-reset-password",
      "feature-src-auth-login-test--user-login-fails-with-invalid-password",
      "feature-src-auth-login-test--user-logs-in-successfully",
    ]);
    expect(index.scenarios.find((scenario) => scenario.title === "User logs in successfully")).toMatchObject({
      title: "User logs in successfully",
      status: "passed",
      sourceFile: "src/auth/login.test.ts",
      tags: ["auth", "login"],
    });

    const schema = JSON.parse(
      fs.readFileSync("schemas/scenario-index-v1.json", "utf8"),
    );
    const validate = new Ajv2020({ strict: false }).compile(schema);
    expect(validate(index)).toBe(true);
  });

  it("filters StoryReport v1 input by status, tag, and source", () => {
    const report = toStoryReport(canonicalizeRun(createMultipleTestCasesRun()));

    expect(toScenarioIndex(report, { statuses: ["failed"] }).scenarios).toHaveLength(1);
    expect(toScenarioIndex(report, { tags: ["password-reset"] }).scenarios).toHaveLength(1);
    expect(toScenarioIndex(report, { sourceFiles: ["login.test.ts"] }).scenarios).toHaveLength(3);
  });

  it("is generated by ReportGenerator", async () => {
    const writes = new Map<string, string>();
    const generator = new ReportGenerator(
      {
        formats: ["scenario-index-json"],
        outputDir: "reports",
        outputName: "index",
      },
      {
        writeFile: async (filePath, content) => {
          writes.set(filePath, content);
        },
      },
    );

    const result = await generator.generate(canonicalizeRun(createMultipleTestCasesRun()));

    expect(result.get("scenario-index-json")).toEqual([
      "reports/index.scenario-index.json",
    ]);
    expect(JSON.parse(writes.get("reports/index.scenario-index.json") ?? "{}").scenarios).toHaveLength(3);
  });
});
