// @ts-check
import starlight from '@astrojs/starlight';
import astroMermaid from 'astro-mermaid';
import remarkGfm from 'remark-gfm';
import { defineConfig } from 'astro/config';

/*
 * Available themes (match HTML formatter themes):
 *   default    — cucumber green, IBM Plex typography
 *   corporate  — navy, Playfair Display serif headings
 *   terminal   — green-on-dark, JetBrains Mono, flat
 *   minimal    — teal, Noto Serif Display headings, warm neutrals
 *   dashboard  — blue, DM Sans + JetBrains Mono
 *   playful    — coral, rounded corners, Source Sans 3
 *
 * To switch themes, replace `themes/default.css` below with the filename
 * of the theme you want (e.g. `./src/styles/themes/corporate.css`).
 */

export default defineConfig({
  // GFM tables don't render in .mdx by default — enable them so hand-written
  // and generated .mdx pages (ADRs, API coverage, decision logs) show tables.
  markdown: {
    remarkPlugins: [remarkGfm],
  },
  integrations: [
    astroMermaid(),
    starlight({
      title: 'Story Docs',
      description: 'Living documentation generated from executable stories.',
      // Renders a live verification badge under the title of any page that
      // declares `verifiedBy` in its frontmatter.
      components: {
        PageTitle: './src/components/PageTitle.astro',
      },
      sidebar: [
        { label: 'Home', slug: 'index' },
        { label: 'Explorer', link: '/explorer/' },
        // Hand-written content — edited by the team, never overwritten by a regenerate.
        { label: 'Guides', autogenerate: { directory: 'guides' } },
        { label: 'Notes', autogenerate: { directory: 'notes' } },
        // Autogenerated, not a hard-coded slug — clearing the sample ADR (or the
        // whole directory) leaves the build green instead of 404ing on a missing slug.
        { label: 'Examples', autogenerate: { directory: 'examples' } },
        // Generated from tests by `format --format astro`.
        {
          label: 'Stories',
          autogenerate: { directory: 'stories' },
        },
      ],
      customCss: [
        './src/styles/global.css',
        './src/styles/themes/default.css',
      ],
    }),
  ],
});
